export const FileTypes: {
  [key: string]: string[];
} = {
  font: [
    'otf',
    'ttf',
    'woff',
    'application/x-font-ttf',
    'application/vnd.ms-opentype',
  ],

  archive: [
    'zip',
    'gz',
    'tar.gz',
    'rar',
    'application/zip',
    'application/gzip',
    'application/x-rar-compressed',
  ],

  text: [
    'txt',
    'text/plain'
  ],

  document: [
    'doc',
    'docx',
    'csv',
    'djvu',
    'odp',
    'ods',
    'odt',
    'ott',
    'pdf',
    'ppt',
    'rtf',
    'xls',
    'xlsx',
    'fm2',
    'mobi',
    'application/epub+zip',
    'application/pdf',
    'application/json',
    'application/msword',
    'application/html',
    'text/html',
    'application/plain',
    'application/csv',
    'application/vnd.oasis.opendocument.text',
    'application/vnd.oasis.opendocument.spreadsheet',
    'application/vnd.oasis.opendocument.presentation',
    'application/vnd.oasis.opendocument.graphics',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-excel.sheet.macroEnabled.12',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  ],

  audio: [
    'aac',
    'ac3',
    'flac',
    'm4a',
    'mp3',
    'ogg',
    'wav',
    'audio/webm',
    'audio/mp4',
    'audio/aac',
    'audio/mpeg',
    'audio/ogg',
    'audio/webm',
  ],

  image: [
    'image/gif',
    'image/jpeg',
    'image/pjpeg',
    'image/png',
    'image/svg+xml',
    'image/tiff',
    'image/vnd.microsoft.icon',
    'image/webp',
    'bmp',
    'cur',
    'gif',
    'hdr',
    'heic',
    'heif',
    'ico',
    'jfif',
    'jfif',

  ],

  video: [
    'video/mpeg',
    'video/mp4',
    'video/ogg',
    'video/quicktime',
    'video/webm',
    'video/x-ms-wmv',
    'video/x-flv',
    'video/x-msvideo',
    'video/3gpp',
    'video/3gpp2',
    'video/x-matroska',
    '3gp',
    'asf',
    'avi',
    'flv',
    'mp4',
    'mpeg',
    'wmv',
    'hevc',
    'mkv',
    'mov',
    'mpg',
  ]
};

